### ISSUE TITLE
cooking is broken

### ISSUE THREAD

**Issue by mufasas111** [modo-lv/qud-mod-skill-training#3]
when selecting items to cook with- there is no accept option- you can only cancel the cooking

you still get exp for the skill mod- so you can spam canceling the recipe getting no benefits except skill xp

**Comment by modo-lv** [comment]
Thanks, but skill training mod is still in development, it's not ready for playing.

**Comment by mufasas111** [comment]
Can i disable that part of the mod and use the rest?
like if i delete the skill training file or something?

**Comment by mufasas111** [comment]
Nvm cooking works- the base game ui is just bad i gaslighted myself thinking it was borked
how was i supposednto think scrolling all the way to top to confirm was how it worked- when none of the ui in any other screen does that?
cancel+confirm has always been next to each other- except for cooking.
rant over
